import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const css = readFileSync(new URL("../app/engine/engine.css", import.meta.url), "utf8");
const topProspectsWorkspace = readFileSync(new URL("../components/engine/TopProspectsWorkspace.tsx", import.meta.url), "utf8");
const autonomousGrowthWorkspace = readFileSync(new URL("../components/engine/AutonomousGrowthWorkspace.tsx", import.meta.url), "utf8");
const discoveryFunnel = readFileSync(new URL("../components/engine/DiscoveryFunnel.tsx", import.meta.url), "utf8");
const systemWorkspace = readFileSync(new URL("../components/engine/SystemWorkspace.tsx", import.meta.url), "utf8");
const prospectWebsitePreview = readFileSync(new URL("../components/engine/ProspectWebsitePreview.tsx", import.meta.url), "utf8");
const tradePreviewImage = readFileSync(new URL("../components/engine/TradePreviewImage.tsx", import.meta.url), "utf8");
const prospectEngineWorkspace = readFileSync(new URL("../components/ProspectEngine.tsx", import.meta.url), "utf8");
const prospectEngine = readFileSync(new URL("../lib/prospect-engine.ts", import.meta.url), "utf8");
const topProspectWorker = readFileSync(new URL("../lib/top-prospect-worker.ts", import.meta.url), "utf8");
const topProspectRepository = readFileSync(new URL("../lib/top-prospect-repository.ts", import.meta.url), "utf8");
const mobileStart = css.indexOf("@media (max-width: 767px)");
const mobileEnd = css.indexOf("@media (max-width: 420px)");
const mobileCss = css.slice(mobileStart, mobileEnd);

test("engine phone layout uses a single-column form flow", () => {
  assert.notEqual(mobileStart, -1);
  assert.match(mobileCss, /\.engine-top-prospect-launcher form\s*{\s*grid-template-columns: 1fr;/);
  assert.match(mobileCss, /\.engine-discovery-form\s*{\s*grid-template-columns: 1fr;/);
  assert.match(mobileCss, /\.engine-score-grid,\s*\.engine-two-col,\s*\.engine-form-grid\s*{\s*grid-template-columns: 1fr;/);
});

test("engine phone layout removes desktop-width result overflow", () => {
  assert.match(mobileCss, /\.engine-table__head\s*{\s*display: none;/);
  assert.match(mobileCss, /\.engine-table > article\s*{\s*min-width: 0;/);
  assert.match(mobileCss, /\.engine-table-main\s*{\s*grid-template-columns: minmax\(0, 1fr\);/);
  assert.match(mobileCss, /\.engine-pipeline\s*{\s*grid-template-columns: 1fr;\s*overflow-x: visible;/);
  assert.match(mobileCss, /\.engine-top-table article\s*{\s*min-width: 0;\s*grid-template-columns: 1fr;/);
  assert.doesNotMatch(mobileCss, /min-width:\s*36rem/);
  assert.match(mobileCss, /\.engine-provider-diagnostic dl\s*{\s*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
  assert.match(mobileCss, /\.engine-trade-diagnostics \[role="row"\]\s*{\s*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
  assert.match(mobileCss, /\.engine-auto-queue__summary\s*{\s*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
  assert.match(mobileCss, /\.engine-autonomous-settings\s*{\s*grid-template-columns: 1fr;/);
  assert.match(mobileCss, /\.engine-autonomous-table article\s*{\s*padding: 0\.85rem;/);
  assert.match(css, /\.engine-autonomous-table__head,\s*\.engine-autonomous-table article\s*{\s*display: grid;/);
});

test("engine phone controls and navigation account for iPhone interaction constraints", () => {
  assert.match(css, /padding-bottom: calc\(var\(--engine-mobile-nav-height\) \+ env\(safe-area-inset-bottom\)\)/);
  assert.match(css, /--engine-mobile-nav-height: 4\.65rem/);
  assert.match(css, /--engine-safe-bottom: env\(safe-area-inset-bottom\)/);
  assert.match(css, /\.engine-sidebar\s*{\s*display: none;/);
  assert.match(css, /\.engine-mobile-bottom-nav\s*{\s*position: fixed;[\s\S]*padding: 0\.35rem 0\.35rem calc\(0\.35rem \+ env\(safe-area-inset-bottom\)\)/);
  assert.match(css, /\.engine-mobile-more-sheet\.is-open\s*{\s*display: grid;/);
  assert.match(css, /\.engine-mobile-more-sheet\s*{[\s\S]*border-radius: var\(--engine-radius-lg\)/);
  assert.match(css, /\.engine-mobile-more-sheet > div > button:active\s*{\s*transform: translateY\(1px\);/);
  assert.match(css, /\.engine-mobile-more-backdrop\s*{\s*position: fixed;/);
  assert.match(mobileCss, /\.engine-section-tabs\s*{\s*display: flex;\s*flex-wrap: nowrap;\s*overflow-x: auto;/);
  assert.match(mobileCss, /\.engine-detail\s*{\s*position: fixed;/);
  assert.match(mobileCss, /\.engine-mobile-action-bar\s*{\s*position: sticky;/);
  assert.match(mobileCss, /\.engine-filter-drawer summary\s*{\s*display: flex;/);
  assert.match(mobileCss, /\.engine-action-label-full\s*{\s*display: none;/);
  assert.match(mobileCss, /\.engine-action-label-short\s*{\s*display: inline;/);
  assert.match(mobileCss, /\.engine-top-prospect-launcher button\s*{\s*width: 100%;/);
  assert.match(mobileCss, /min-height: 2\.45rem;\s*font-size: 0\.92rem;/);
  assert.match(mobileCss, /\.engine-empty__actions \.engine-button\s*{\s*width: 100%;/);
  assert.match(mobileCss, /\.engine-inline-actions \.engine-button\s*{\s*width: 100%;/);
  assert.match(mobileCss, /\.engine-prospect-labels span,/);
});

test("desktop navigation collapse toggle remains visible, accessible, and reversible", () => {
  const toggleMarkup = prospectEngineWorkspace.match(/<button\s+aria-expanded=\{!sidebarCollapsed\}[\s\S]*?className="engine-nav-collapse"[\s\S]*?<\/button>/)?.[0] ?? "";

  assert.ok(toggleMarkup, "expected one persistent navigation toggle");
  assert.equal((prospectEngineWorkspace.match(/className="engine-nav-collapse"/g) ?? []).length, 1);
  assert.match(prospectEngineWorkspace, /sidebarToggleLabel = sidebarCollapsed \? "Expand navigation" : "Collapse navigation"/);
  assert.match(toggleMarkup, /aria-label=\{sidebarToggleLabel\}/);
  assert.match(toggleMarkup, /aria-expanded=\{!sidebarCollapsed\}/);
  assert.match(toggleMarkup, /title=\{sidebarCollapsed \? sidebarToggleLabel : undefined\}/);
  assert.match(toggleMarkup, /onClick=\{\(\) => setSidebarCollapsed\(\(current\) => !current\)\}/);
  assert.match(toggleMarkup, /event\.key !== "Enter" && event\.key !== " "/);
  assert.match(toggleMarkup, /event\.preventDefault\(\)/);
  assert.match(toggleMarkup, /type="button"/);
  assert.doesNotMatch(toggleMarkup, /navigateWorkspace|window\.location|href=/);
  assert.match(prospectEngineWorkspace, /className=\{workspaceTab === tab \? "is-active" : ""\}/);
  assert.doesNotMatch(css, /\.engine-shell--nav-collapsed \.engine-nav-collapse(?:,|\s*\{)[^}]*display:\s*none/);
  assert.match(css, /\.engine-shell--nav-collapsed \.engine-nav-collapse\s*\{\s*width: 3\.3rem;/);
  assert.match(css, /\.engine-shell--nav-collapsed \.engine-nav-collapse:hover \.engine-nav-collapse__tooltip,[\s\S]*\.engine-shell--nav-collapsed \.engine-nav-collapse:focus-visible \.engine-nav-collapse__tooltip\s*\{[\s\S]*visibility: visible;/);
});

test("engine phone command center and overview stay compact", () => {
  assert.match(css, /\.engine-command-bar\s*{\s*display: grid;\s*grid-template-columns: minmax\(16rem, 1fr\) auto auto auto auto auto;/);
  assert.match(mobileCss, /\.engine-command-center__summary\s*{\s*display: block;/);
  assert.match(mobileCss, /\.engine-command-center__body\s*{\s*display: none;\s*padding-top: 0\.55rem;/);
  assert.match(mobileCss, /\.engine-command-center\.is-mobile-expanded \.engine-command-center__body\s*{\s*display: block;/);
  assert.match(mobileCss, /\.engine-command-bar\s*{\s*grid-template-columns: 1fr;/);
  assert.match(css, /\.engine-overview-cards\s*{\s*display: grid;\s*grid-template-columns: repeat\(6, minmax\(0, 1fr\)\);/);
  assert.match(mobileCss, /\.engine-overview-cards\s*{\s*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/);
  assert.match(css, /@media \(max-width: 420px\)[\s\S]*\.engine-overview-cards\s*{\s*grid-template-columns: 1fr;/);
  assert.match(css, /@media \(prefers-reduced-motion: reduce\)[\s\S]*transition-duration: 1ms !important;/);
});

test("Autonomous Growth tab exposes safe modes, queue controls, and CSV export", () => {
  assert.match(prospectEngineWorkspace, /Autonomous Growth/);
  assert.match(autonomousGrowthWorkspace, /Safe autonomous prospecting/);
  assert.match(autonomousGrowthWorkspace, /Autopilot Campaign/);
  assert.match(autonomousGrowthWorkspace, /Choose Autopilot Market/);
  assert.match(autonomousGrowthWorkspace, /Recommended first real run: Florida \+ Pressure Washing/);
  assert.match(autonomousGrowthWorkspace, /autopilotMarketPickerPresetIds/);
  assert.match(autonomousGrowthWorkspace, /northwest-ohio/);
  assert.match(autonomousGrowthWorkspace, /florida/);
  assert.match(autonomousGrowthWorkspace, /texas-suburbs/);
  assert.match(autonomousGrowthWorkspace, /carolinas-tennessee-georgia/);
  assert.match(autonomousGrowthWorkspace, /ohio-midwest/);
  assert.match(autonomousGrowthWorkspace, /arizona-nevada/);
  assert.match(autonomousGrowthWorkspace, /autopilotQuickTrades/);
  assert.match(autonomousGrowthWorkspace, /Pressure Washing/);
  assert.match(autonomousGrowthWorkspace, /updateMarketTrade/);
  assert.match(autonomousGrowthWorkspace, /recommendedFirstAutopilotRunSettings/);
  assert.match(autonomousGrowthWorkspace, /Start Autopilot with:/);
  assert.match(autonomousGrowthWorkspace, /startConfirmation\.safety/);
  assert.match(autonomousGrowthWorkspace, /autoPilotBlocked \? "Emails: blocked or review-only" : "Emails: approved queue only"/);
  assert.match(autonomousGrowthWorkspace, /autoPilotBlocked \? pilotGateReasons\.join\(" "\) : "Only explicitly approved queued public-email drafts may send through Auto Email Pilot\. Other channels remain manual\."/);
  assert.match(autonomousGrowthWorkspace, /Social DMs: manual only/);
  assert.match(autonomousGrowthWorkspace, /Contact forms: never automated/);
  assert.match(autonomousGrowthWorkspace, /Phone calls: never automated/);
  assert.match(autonomousGrowthWorkspace, /Looms: manual only/);
  assert.match(autonomousGrowthWorkspace, /marketMismatchWarning/);
  assert.match(autonomousGrowthWorkspace, /providerGuardrailWarnings/);
  assert.match(autonomousGrowthWorkspace, /Provider coverage is limited\. Run Provider Smoke Test or a small Top Prospects test before starting Autopilot\./);
  assert.match(autonomousGrowthWorkspace, /updateMarketPreset/);
  assert.match(autonomousGrowthWorkspace, /autopilotPresetFields/);
  assert.match(autonomousGrowthWorkspace, /value=\{formSettings\.marketPresetId\}/);
  assert.match(autonomousGrowthWorkspace, /value=\{formSettings\.customCities\}/);
  assert.match(autonomousGrowthWorkspace, /value=\{formSettings\.state\}/);
  assert.match(autonomousGrowthWorkspace, /Autopilot Live Activity/);
  assert.match(autonomousGrowthWorkspace, /No Autopilot activity yet\. Start Autopilot or run the fake smoke test to see live steps\./);
  assert.match(autonomousGrowthWorkspace, /Fake Smoke Test Activity — no providers, no outreach\./);
  assert.match(autonomousGrowthWorkspace, /Refresh Activity/);
  assert.match(autonomousGrowthWorkspace, /Current status/);
  assert.match(autonomousGrowthWorkspace, /Current step/);
  assert.match(autonomousGrowthWorkspace, /Provider diagnostics/);
  assert.match(autonomousGrowthWorkspace, /City breakdown/);
  assert.match(autonomousGrowthWorkspace, /Blocked reasons/);
  assert.match(autonomousGrowthWorkspace, /Queue routing/);
  assert.match(autonomousGrowthWorkspace, /Next recommended run/);
  assert.match(autonomousGrowthWorkspace, /Start Autopilot/);
  assert.match(autonomousGrowthWorkspace, /Pause/);
  assert.match(autonomousGrowthWorkspace, /Resume/);
  assert.match(autonomousGrowthWorkspace, /Stop/);
  assert.match(autonomousGrowthWorkspace, /Run next batch now/);
  assert.match(autonomousGrowthWorkspace, /Run Fake Smoke Test/);
  assert.match(autonomousGrowthWorkspace, /Uses fake leads only\. No provider calls\. No outreach\./);
  assert.match(autonomousGrowthWorkspace, /Start Autopilot prepares prospects, previews, scripts, and queues\. It does not send emails, DMs, forms, phone calls, or Looms automatically\./);
  assert.match(autonomousGrowthWorkspace, /engine-autopilot-action-card/);
  assert.match(autonomousGrowthWorkspace, /engine-autopilot-disabled-reasons/);
  assert.match(autonomousGrowthWorkspace, /missing market/);
  assert.match(autonomousGrowthWorkspace, /missing trade/);
  assert.match(autonomousGrowthWorkspace, /invalid city/);
  assert.match(autonomousGrowthWorkspace, /campaign already running/);
  assert.match(autonomousGrowthWorkspace, /Autopilot is disabled by environment kill switch\./);
  assert.match(autonomousGrowthWorkspace, /no database connection/);
  assert.match(autonomousGrowthWorkspace, /safety setting required/);
  assert.equal((autonomousGrowthWorkspace.match(/<AutopilotActionRow/g) ?? []).length, 2);
  assert.match(autonomousGrowthWorkspace, /Ready for Manual DM/);
  assert.match(autonomousGrowthWorkspace, /Needs Preview Review/);
  assert.match(autonomousGrowthWorkspace, /Email Draft Ready/);
  assert.match(autonomousGrowthWorkspace, /Blocked \/ Bad Fit/);
  assert.match(autonomousGrowthWorkspace, /Counts shown below come from the latest run report\. Fake smoke-test counts do not create saved outreach items\./);
  assert.match(autonomousGrowthWorkspace, /Counts shown below come from saved outreach queue items\./);
  assert.match(autonomousGrowthWorkspace, /No email, form, social, phone, or Loom outreach is sent automatically/);
  assert.match(topProspectsWorkspace, /autopilotCampaignDraftStorageKey/);
  assert.match(topProspectsWorkspace, /autopilotDraftFromRecommendedMarket/);
  assert.match(autonomousGrowthWorkspace, /You have Loom walkthroughs to record/);
  assert.match(autonomousGrowthWorkspace, /Loom Needed Queue/);
  assert.match(autonomousGrowthWorkspace, /Review-before-Loom checklist/);
  assert.match(autonomousGrowthWorkspace, /Copy first DM/);
  assert.match(autonomousGrowthWorkspace, /Copy Loom script/);
  assert.match(autonomousGrowthWorkspace, /Copy \$49\/month pricing/);
  assert.match(autonomousGrowthWorkspace, /Prospect Said Yes/);
  assert.match(autonomousGrowthWorkspace, /Preview Needs Polish/);
  assert.match(autonomousGrowthWorkspace, /Ready for Loom/);
  assert.match(autonomousGrowthWorkspace, /Loom Recorded/);
  assert.match(autonomousGrowthWorkspace, /Loom Sent/);
  assert.match(autonomousGrowthWorkspace, /Outreach mode/);
  assert.match(autonomousGrowthWorkspace, /Global kill switch/);
  assert.match(autonomousGrowthWorkspace, /Dry Run/);
  assert.match(autonomousGrowthWorkspace, /Manual Approval/);
  assert.match(autonomousGrowthWorkspace, /Auto Email Pilot/);
  assert.match(autonomousGrowthWorkspace, /Export CSV/);
  assert.match(autonomousGrowthWorkspace, /Auto Email Pilot gates/);
  assert.match(autonomousGrowthWorkspace, /Email Send &amp; Suppression History/);
  assert.match(autonomousGrowthWorkspace, /Queued public-email sends/);
  assert.match(autonomousGrowthWorkspace, /Latest suppression/);
  assert.match(autonomousGrowthWorkspace, /Only Queued public-email leads can send/);
  assert.match(autonomousGrowthWorkspace, /Daily cap, cooldown, suppression, and audit logs enforced/);
  assert.match(autonomousGrowthWorkspace, /OUTREACH_EMAIL_DISABLED is not true/);
  assert.match(autonomousGrowthWorkspace, /Fully automatic batch sending is separate from/);
  assert.match(autonomousGrowthWorkspace, /OUTREACH_FULL_AUTO_SEND_ENABLED=true/);
  assert.match(autonomousGrowthWorkspace, /Run full auto email batch/);
  assert.match(autonomousGrowthWorkspace, /Send approved email/);
  assert.match(autonomousGrowthWorkspace, /Mark bounced/);
  assert.match(autonomousGrowthWorkspace, /Mark complained/);
  assert.match(autonomousGrowthWorkspace, /Suppress email/);
  assert.match(autonomousGrowthWorkspace, /Learning &amp; Review/);
  assert.match(autonomousGrowthWorkspace, /Latest self-review summary/);
  assert.match(autonomousGrowthWorkspace, /Recommendations for next run/);
  assert.match(autonomousGrowthWorkspace, /Regenerate with Fixes/);
  assert.match(autonomousGrowthWorkspace, /Rewrite Outreach/);
  assert.match(autonomousGrowthWorkspace, /autonomousFeedbackLabels/);
  assert.match(autonomousGrowthWorkspace, /Editable trade style profiles/);
  assert.match(autonomousGrowthWorkspace, /Mark reviewed/);
  assert.match(autonomousGrowthWorkspace, /Dry-run and review queue/);
  assert.match(autonomousGrowthWorkspace, /Export CSV/);
  assert.match(autonomousGrowthWorkspace, /review score/);
  assert.match(css, /\.engine-autonomous-hero\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-action-card\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-market-picker\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-market-picker__grid\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-market-picker__trades\s*{\s*display: flex;/);
  assert.match(css, /\.engine-autopilot-start-confirmation,/);
  assert.match(css, /\.engine-autopilot-market-warning\s*{\s*border-color: #e2c17b;/);
  assert.match(css, /\.engine-autopilot-provider-warning\s*{\s*border-color: #e2c17b;/);
  assert.match(css, /\.engine-autopilot-activity\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-activity__head\s*{\s*display: flex;/);
  assert.match(css, /\.engine-autopilot-activity-grid\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-activity-metrics\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-timeline\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-details__grid\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-form\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-actions\s*{\s*display: flex;/);
  assert.match(css, /\.engine-autopilot-fake-button\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-disabled-reasons\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autopilot-queues\s*{\s*display: grid;/);
  assert.match(mobileCss, /\.engine-autopilot-activity-grid,/);
  assert.match(mobileCss, /\.engine-autopilot-market-picker__head,/);
  assert.match(mobileCss, /\.engine-autopilot-market-picker__trades \.engine-chip-button\s*{\s*width: 100%;/);
  assert.match(mobileCss, /\.engine-autopilot-activity__head\s*{\s*align-items: stretch;\s*flex-direction: column;/);
  assert.match(mobileCss, /\.engine-autopilot-timeline__item\s*{\s*grid-template-columns: 1fr;/);
  assert.match(css, /\.engine-safety-grid\s*{\s*display: grid;/);
  assert.match(css, /\.engine-autonomous-table \.engine-result-actions\s*{\s*display: flex;\s*flex-wrap: wrap;/);
  assert.match(css, /\.engine-learning-summary\s*{\s*display: grid;/);
  assert.match(css, /\.engine-feedback-controls\s*{\s*display: grid;/);
  assert.match(css, /\.engine-reply-table\s*{\s*display: grid;/);
  assert.match(css, /\.engine-loom-banner\s*{\s*display: flex;/);
  assert.match(css, /\.engine-loom-task__facts\s*{\s*grid-template-columns:/);
  assert.match(css, /\.engine-script-grid\s*{\s*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\);/);
  assert.match(css, /\.engine-loom-actions\s*{\s*grid-template-columns: repeat\(6, minmax\(0, 1fr\)\);/);
});

test("protected prospect previews remain readable and business-themed on phones", () => {
  assert.match(mobileCss, /\.prospect-preview-site\[data-layout="project-led"\] \.prospect-preview-hero,/);
  assert.match(mobileCss, /\.prospect-preview-nav div\s*{\s*display: none;/);
  assert.match(mobileCss, /\.prospect-preview-actions\s*{\s*align-items: stretch;\s*flex-direction: column;/);
  assert.match(mobileCss, /\.prospect-preview-image--hero\s*{\s*aspect-ratio: 4 \/ 3;/);
  assert.match(mobileCss, /\.prospect-preview-service-list article,\s*\.prospect-preview-service-list article:first-child\s*{\s*grid-column: 1 \/ -1;\s*grid-template-columns: 1fr;/);
  assert.match(mobileCss, /\.prospect-preview-contact form\s*{\s*grid-template-columns: 1fr;/);
  assert.match(mobileCss, /\.prospect-preview-footer\s*{\s*flex-direction: column;/);
  assert.match(mobileCss, /\.prospect-preview-why,/);
  assert.doesNotMatch(css, /--preview-green|--preview-lime/);
  assert.match(css, /prospect-preview-visual-caption/);
  assert.doesNotMatch(prospectWebsitePreview, /picsum\.photos/);
  assert.match(prospectWebsitePreview, /resolvePreviewImages/);
  assert.match(prospectWebsitePreview, /previewImageProps/);
  assert.match(tradePreviewImage, /data-preview-image-source/);
  assert.match(tradePreviewImage, /onError={handleImageError}/);
  assert.doesNotMatch(tradePreviewImage, /Image unavailable|The rest of this preview is still available/);
  assert.doesNotMatch(tradePreviewImage, /fallbackSrc|data-fallback-src/);
  assert.match(css, /contain: layout paint;/);
  assert.match(css, /@media \(max-width: 980px\)[\s\S]*\.prospect-preview-process,\s*\.prospect-preview-proof-layout\s*{\s*grid-template-columns: minmax\(0, 1fr\);/);
  assert.match(mobileCss, /\.prospect-preview-process ol,/);
  assert.doesNotMatch(prospectWebsitePreview, /prospect-preview-visual__mark|TradeVisualPanel/);
});

test("Outreach Package bulk review exposes the complete human approval workflow on mobile", () => {
  assert.match(topProspectsWorkspace, /Outreach Package Review/);
  assert.match(topProspectsWorkspace, /Generate Outreach Package/);
  assert.match(topProspectsWorkspace, /Review preview \+ email/);
  assert.match(topProspectsWorkspace, /Approve to Send/);
  assert.match(topProspectsWorkspace, /Email quality checks/);
  assert.match(topProspectsWorkspace, /check\.phrase/);
  assert.match(topProspectsWorkspace, /check\.reason/);
  assert.match(topProspectsWorkspace, /check\.suggestion/);
  assert.match(topProspectsWorkspace, /Public preview link/);
  assert.match(topProspectsWorkspace, /Send-ready/);
  assert.match(topProspectsWorkspace, /Phone-only \/ written outreach blocked/);
  assert.match(topProspectsWorkspace, /Missing written contact method/);
  assert.match(topProspectsWorkspace, /Mark Sent/);
  assert.match(topProspectsWorkspace, /Skip/);
  assert.match(topProspectsWorkspace, /Open Lovable/);
  assert.match(topProspectsWorkspace, /Open Bolt/);
  assert.match(topProspectsWorkspace, /Open v0/);
  assert.match(topProspectsWorkspace, /Casual DM \+ Loom playbook/);
  assert.match(topProspectsWorkspace, /First Facebook or Instagram DM does not include the preview link/);
  assert.match(topProspectsWorkspace, /Copy first DM/);
  assert.match(topProspectsWorkspace, /Copy Loom send message/);
  assert.match(topProspectsWorkspace, /Copy \$500 starter page/);
  assert.match(autonomousGrowthWorkspace, /engine-loom-recommendation/);
  assert.match(autonomousGrowthWorkspace, /Current-site issue to show/);
  assert.match(autonomousGrowthWorkspace, /Preview improvement to show/);
  assert.match(autonomousGrowthWorkspace, /Public preview link/);
  assert.match(mobileCss, /\.engine-package-review-grid,\s*\.engine-package-dialog__summary,\s*\.engine-email-quality ul\s*{\s*grid-template-columns: 1fr;/);
  assert.match(mobileCss, /\.engine-package-card__actions\s*{\s*grid-template-columns: 1fr;/);
  assert.match(mobileCss, /\.engine-email-quality li > b\s*{\s*font-size: 0\.875rem;/);
  assert.match(mobileCss, /\.engine-loom-task__facts,\s*\.engine-loom-recommendation dl,\s*\.engine-script-grid,\s*\.engine-loom-actions\s*{\s*grid-template-columns: 1fr;/);
});

test("Top Prospects exposes modes, background batch workflow, queue, and requested score labels", () => {
  assert.match(topProspectsWorkspace, /Prospect mode/);
  assert.match(topProspectsWorkspace, /allCoreServiceTradesOption/);
  assert.match(prospectEngine, /All Core Service Trades/);
  assert.match(topProspectsWorkspace, /useState<ProspectMode>\("growth"\)/);
  assert.match(topProspectsWorkspace, /useState<ProspectSearchType>\("all"\)/);
  assert.match(topProspectsWorkspace, /useState<TopProspectJob\["input"\]\["trade"\]>\("Landscaping"\)/);
  assert.match(topProspectsWorkspace, /useState\(100\)/);
  assert.match(topProspectsWorkspace, /useState\(20\)/);
  assert.match(topProspectsWorkspace, /useState\(50\)/);
  assert.match(topProspectsWorkspace, /value=\{selectedRadiusKm\}/);
  assert.match(topProspectsWorkspace, /value=\{businessesToScan\}/);
  assert.match(topProspectsWorkspace, /value=\{finalProspectsWanted\}/);
  assert.match(topProspectsWorkspace, /total budget across all selected cities and trades/);
  assert.match(topProspectsWorkspace, /Recommended Markets/);
  assert.match(topProspectsWorkspace, /Click Use this market to fill the city field, or click a trade to fill the market and trade together\. You still need to click Find Top Prospects or Start Autopilot\./);
  assert.match(topProspectsWorkspace, /shouldShowLimitedProviderCoverageWarning/);
  assert.doesNotMatch(topProspectsWorkspace, /This run may return very few prospects until Google Places or Yelp is configured/);
  assert.match(topProspectsWorkspace, /providerCoverage\.recommendation/);
  assert.match(topProspectsWorkspace, /Radius <b>\{latestJob\.input\.radiusKm\} km<\/b>/);
  assert.match(topProspectsWorkspace, /Scan budget <b>\{latestJob\.input\.businessesToScan\}<\/b>/);
  assert.match(topProspectsWorkspace, /Run settings used: \{latestJob\.input\.radiusKm\} km radius/);
  assert.match(topProspectsWorkspace, /engine-market-actions/);
  assert.match(topProspectsWorkspace, /Use this market/);
  assert.match(topProspectsWorkspace, /Add to current cities/);
  assert.match(topProspectsWorkspace, /Use recommended trades/);
  assert.match(topProspectsWorkspace, /Use \$\{preset\.name\} with \$\{displayTradeCategory\(trade\)\}/);
  assert.match(topProspectsWorkspace, /type="button">Use this market/);
  assert.match(topProspectsWorkspace, /type="button">Add to current cities/);
  assert.match(topProspectsWorkspace, /type="button">Use recommended trades/);
  assert.doesNotMatch(topProspectsWorkspace, /applyPreset\([^)]*\);\s*void startJob/s);
  assert.match(mobileCss, /\.engine-market-actions,\s*\.engine-market-actions \.engine-button,\s*\.engine-chip-button\s*{\s*width: 100%;/);
  assert.match(topProspectsWorkspace, /Exclude previously reviewed prospects/);
  assert.match(topProspectsWorkspace, /Discovery complete\. Analyze/);
  assert.match(topProspectsWorkspace, /Analyze saved prospects/);
  assert.match(topProspectsWorkspace, /discovery complete, waiting to analyze/);
  assert.match(topProspectsWorkspace, /latestJob && latestJob\.scannedCount > 0 \? latestJob\.results\[0\] : null/);
  assert.match(topProspectsWorkspace, /Website scan/);
  assert.match(topProspectsWorkspace, /Preview generation/);
  assert.match(topProspectsWorkspace, /Outreach packages/);
  assert.match(topProspectsWorkspace, /NEEDS_NEXT_BATCH/);
  assert.match(topProspectsWorkspace, /PARTIAL_RESULTS_READY/);
  assert.match(topProspectWorker, /BATCH_SIZE = 3/);
  assert.match(topProspectWorker, /waitingStatusForDiscovery/);
  assert.match(topProspectWorker, /Saved discovery found; resuming analysis without rediscovery/);
  assert.match(topProspectWorker, /status: partialStatus/);
  assert.match(topProspectWorker, /stage: "ANALYZE"/);
  assert.match(topProspectWorker, /status: done \? "RUNNING" : waitingStatus/);
  assert.match(topProspectRepository, /reconcileStaleTopProspectJobs/);
  assert.match(topProspectRepository, /staleRunningMs = 10 \* 60_000/);
  assert.match(topProspectRepository, /stage: "DISCOVER",\s*OR: \[\{ leaseUntil: null \}, \{ leaseUntil: \{ lte: now \} \}\]/);
  assert.match(topProspectRepository, /inferredScannedCount/);
  assert.match(topProspectsWorkspace, /Outreach preference/);
  assert.match(topProspectsWorkspace, /Written outreach only/);
  assert.match(topProspectsWorkspace, /Phone allowed/);
  assert.match(topProspectsWorkspace, /Email available/);
  assert.match(topProspectsWorkspace, /Contact form available/);
  assert.match(topProspectsWorkspace, /Social message available/);
  assert.match(topProspectsWorkspace, /Hide phone-only leads/);
  assert.match(topProspectsWorkspace, /Send-ready only/);
  assert.match(topProspectsWorkspace, /Needs contact research/);
  assert.match(prospectEngineWorkspace, /Filter by contact method/);
  assert.match(topProspectsWorkspace, /Morning Prospect Batch/);
  assert.match(topProspectsWorkspace, /Auto Prospect Queue/);
  assert.match(topProspectsWorkspace, /packageReviewableCount/);
  assert.match(topProspectsWorkspace, /package\{packageReviewableCount === 1 \? "" : "s"\} to review/);
  assert.match(topProspectsWorkspace, /Preview generated, outreach blocked: phone-only\./);
  assert.match(topProspectsWorkspace, /Ranked Top Prospects/);
  assert.match(discoveryFunnel, /diagnostic\.endpointVersion \?\? "New"/);
  assert.match(systemWorkspace, /provider\.endpointVersion \?\? "New"/);
  assert.match(topProspectsWorkspace, /Reviewable lower-priority packages/);
  assert.match(topProspectsWorkspace, /Blocked prospects/);
  assert.match(topProspectsWorkspace, /Previously reviewed prospects/);
  assert.match(topProspectsWorkspace, /Failed or timed-out discovery/);
  assert.match(topProspectsWorkspace, /Prospect outcome buckets/);
  assert.match(topProspectsWorkspace, /failedProviderDiagnostics/);
  assert.match(topProspectsWorkspace, /failedCityDiagnostics/);
  assert.match(css, /\.engine-outcome-buckets__grid\s*{\s*display: grid;/);
  assert.match(mobileCss, /\.engine-outcome-buckets__grid,\s*\.engine-outcome-detail-grid,\s*\.engine-outcome-skip-list ul\s*{\s*grid-template-columns: 1fr;/);
  assert.match(topProspectsWorkspace, /Final weighted sales/);
  assert.match(topProspectsWorkspace, /Revenue opportunity/);
  assert.match(topProspectsWorkspace, /AI replacement confidence/);
  assert.match(topProspectsWorkspace, /No Website \/ Social Only/);
  assert.match(topProspectsWorkspace, /All Prospect Types/);
  assert.match(prospectEngine, /No website found/);
  assert.match(prospectEngine, /Public email available/);
  assert.match(prospectEngine, /Needs manual contact research/);
  assert.match(topProspectsWorkspace, /prospectPresenceLabels/);
  assert.match(topProspectsWorkspace, /Online presence gap/);
  assert.match(topProspectsWorkspace, /Business activity/);
  assert.match(topProspectsWorkspace, /Local fit/);
  assert.match(topProspectsWorkspace, /Final sales score/);
  assert.match(css, /\.engine-presence-summary\s*{\s*display: flex;\s*flex-wrap: wrap;/);
});
